# Generated by Django 6.1.1 on 2026-10-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('douma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
